checks:
    php:
        code_rating: true
        duplication: true

php_version: 7.2

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
tools:
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        config:
            standard: "PSR12"
    external_code_coverage:
        timeout: 600

global_exclude_dirs:
    - .idea
    - vendors
